# Generated by Django 4.2.7 on 2023-11-10 13:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ADM0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm_name", models.CharField(max_length=255, null=True)),
                ("adm_type", models.CharField(max_length=255, null=True)),
                ("background_story", models.TextField(null=True)),
                (
                    "adm_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="ADM1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm_name", models.CharField(max_length=255, null=True)),
                ("adm_type", models.CharField(max_length=255, null=True)),
                ("background_story", models.TextField(null=True)),
                (
                    "adm_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.adm0",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
