# Generated by Django 4.2.7 on 2023-11-16 00:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("valhko_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADM2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm_name", models.CharField(max_length=255, null=True)),
                ("adm_type", models.CharField(max_length=255, null=True)),
                ("background_story", models.TextField(null=True)),
                (
                    "adm_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.adm1",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ADM3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm_name", models.CharField(max_length=255, null=True)),
                ("adm_type", models.CharField(max_length=255, null=True)),
                ("background_story", models.TextField(null=True)),
                (
                    "adm_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.adm2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ADM4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm_name", models.CharField(max_length=255, null=True)),
                ("adm_type", models.CharField(max_length=255, null=True)),
                ("background_story", models.TextField(null=True)),
                (
                    "adm_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "adm3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.adm3",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
