# Generated by Django 4.2.7 on 2023-11-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("valhko_app", "0003_alter_adm0_options_adm0_climate_finance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adm0",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="adm1",
            options={"verbose_name_plural": "ADM1s"},
        ),
        migrations.AlterModelOptions(
            name="adm2",
            options={"verbose_name_plural": "ADM2s"},
        ),
        migrations.AlterModelOptions(
            name="adm3",
            options={"verbose_name_plural": "ADM3s"},
        ),
        migrations.AlterModelOptions(
            name="adm4",
            options={"verbose_name_plural": "ADM4s"},
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pub_year", models.IntegerField()),
                ("budget", models.FloatField(null=True)),
                ("originator", models.CharField(max_length=255, null=True)),
                ("document_type", models.CharField(max_length=255, null=True)),
                ("document_group", models.CharField(max_length=255, null=True)),
                ("document_file", models.FileField(null=True, upload_to="documents/")),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.adm0",
                    ),
                ),
            ],
            options={
                "ordering": ["pub_year"],
            },
        ),
    ]
