# Generated by Django 4.2.7 on 2023-11-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("valhko_app", "0004_alter_adm0_options_alter_adm1_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_index", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="IndiceValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_index", models.DateField()),
                ("price", models.FloatField()),
                ("benchmark_price", models.FloatField()),
                (
                    "name_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valhko_app.indice",
                    ),
                ),
            ],
        ),
    ]
